### PR TITLE
Fix import of abstract container classes to Python 3.9 compatible module

### PR DESCRIPTION
**Pull request by ch3pjw**
This should address issue #21

### CODE REVIEW

**Comment by kapouille** [comment]
Do you mind fixing the `.travis.yml` to remove versions prior to 3.4 and add versions up to 3.9? Thank you Sir.

**Comment by ch3pjw** [comment]
Yeah, I thought it might fail the CI, I was just being lazy!

**Comment by kapouille** [comment]
Nearly there, it sounds like 3.9 is changing other stuff!

**Comment by ch3pjw** [comment]
I'm just experimenting using `pytest` rather than `nose`

**Comment by ch3pjw** [comment]
Do you use `six` for anything any more?

**Comment by kapouille** [comment]
you are right, 2.x isn't supported anymore, `six` is going

**Pull request merged**
